[package]
name = "potato-head"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
description = "Making prompts simple"

[lib]
doctest = false


[dependencies]
opsml-utils = { workspace = true }

pyo3 = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }