site_name: OpsML
site_url: https://demml.github.io/opsml/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      primary: stylesheets/extra.css
      accent: stylesheets/extra.css
      toggle:
        icon: material/weather-night
        name: "Switch to light mode"

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: stylesheets/extra.css
      accent: stylesheets/extra.css
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: stylesheets/extra.css
      accent: stylesheets/extra.css
      toggle:
        icon: material/weather-sunny
        name: "Switch to system preference"

  features:
    #- content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/gear.png"

repo_name: opsml
repo_url: https://github.com/demml/opsml
edit_uri: edit/main/docs/

nav:
  - Overview: "index.md"
  - Quality Control: "quality_control.md"
  - Installation: "installation.md"
  - Setup: "setup.md"
  #- Quickstart: "quickstart.md"
  #- Reference: "reference.md"
  #- Interfaces:
  #    - "interfaces/overview.md"
  #    - Data Interface:
  #        - "interfaces/data/interfaces.md"
  #        - "interfaces/data/data_splits.md"
  #        - "interfaces/data/datasets.md"
  #        - "interfaces/data/data_profile.md"
  #        - "interfaces/data/feature.md"
#
#    - Model Interface:
#        - "interfaces/model/interfaces.md"
#        - "interfaces/model/onnx.md"
#        - "interfaces/model/extras.md"
#        - "interfaces/model/deployment.md"
#- Cards:
#    - "cards/overview.md"
#    - "cards/versioning.md"
#    - "cards/metadata.md"
#    - DataCard:
#        - "cards/datacard.md"
#    - ModelCard:
#        - "cards/modelcard.md"
#        - "cards/challenger.md"
#    - "cards/experimentcard.md"
#    - "cards/auditcard.md"
#- CLI:
#    - Overview: "cli/overview.md"
#- FAQ:
#    - Common Questions: "faq/common_questions.md"
#- Engineering:
#    - Ownership: "engineering/ownership.md"
#    - Server: "engineering/server.md"
#    - How It Works: "engineering/how-it-works.md"
#- Contributing:
#    - Contributing: "faq/contributing.md"
#- API Documentation:
#    - Specs: "api/index.html"

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - def_list
  - attr_list
  - md_in_html:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        #- pymdownx.superfences:
        #    custom_fences:
        #      - name: python
        #        class: python
        #        format: !!python/name:pymdownx.superfences.fence_code_format
        #- pymdownx.emoji:
        #    emoji_index: !!python/name:material.extensions.emoji.twemoji
        #    emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - search
  - mkdocstrings

extra_css:
  - css/custom.css
  - stylesheets/extra.css
  - css/termynal.css
extra_javascript:
  - js/termynal.js
  - js/custom.js

extra:
  version:
    provider: mike
