kind: pipeline
name: test-and-build-py38
type: docker
workspace:
  base: /usr/src/py38
  path: ${DRONE_REPO_NAME}

trigger:
  event:
  - pull_request

steps:
  - name: py38
    image: python:3.8
    commands:
      - apt update
      - echo $GOOGLE_ACCOUNT_JSON_BASE64 | base64 -d > account.json
      - export GOOGLE_APPLICATION_CREDENTIALS=account.json
      - pip install poetry==1.2.2
      - poetry install --all-extras --with dev,dev-tf
      - make test.unit
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
      GOOGLE_ACCOUNT_JSON_BASE64:
        from_secret: GOOGLE_ACCOUNT_JSON_BASE64

