[package]
name = "opsml-toml"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[lib]
doctest = false

[dependencies]
opsml-types = { workspace = true }
opsml-version = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml_edit = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
opsml-state = { workspace = true }
opsml-cards = { workspace = true }