[package]
name = "opsml-storage"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = "MIT"
description = "Core rust library for the opsml project"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }

aws-config = { workspace = true, optional = true }
aws-sdk-s3 = { workspace = true, optional = true }
azure_identity = { workspace = true, optional = true }
azure_storage = { workspace = true, optional = true }
azure_storage_blobs = { workspace = true, optional = true }

base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }

google-cloud-auth = { workspace = true, optional = true }
google-cloud-storage = { workspace = true, optional = true }

opsml-client = { workspace = true }
opsml-colors = { workspace = true }
opsml-error = { workspace = true }
opsml-settings = { workspace = true }
opsml-state = { workspace = true }
opsml-types = { workspace = true }
opsml-utils = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }

[features]
server = ["aws-config", "aws-sdk-s3", "azure_identity", "azure_storage", "azure_storage_blobs", "google-cloud-auth", "google-cloud-storage"]

[dev-dependencies]
mockall = "0.*"
mockito = "1.*"
rand = "0.*"
tempfile = "3.*"
