[package]
name = "opsml-storage"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = "MIT"
description = "Core rust library for the OpsML"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }

aws-config = { workspace = true, optional = true }
aws-sdk-s3 = { workspace = true, optional = true }
azure_core = { workspace = true, optional = true }
azure_identity = { workspace = true, optional = true }
azure_storage = { workspace = true, optional = true }
azure_storage_blobs = { workspace = true, optional = true }

base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }

gcloud-storage = { workspace = true, optional = true }
gcloud-auth = { workspace = true, optional = true }

indicatif = { workspace = true }

opsml-client = { workspace = true }
opsml-colors = { workspace = true }
opsml-settings = { workspace = true }
opsml-state = { workspace = true }
opsml-types = { workspace = true }
opsml-utils = { workspace = true }
rayon = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }

[features]
default = []
server = ["aws-config", "aws-sdk-s3", "azure_identity", "azure_storage", "azure_storage_blobs", "azure_core", "gcloud-auth", "gcloud-storage"]

[dev-dependencies]
mockall = { workspace = true }
mockito = { workspace = true }
rand = "0.*"
tempfile = {workspace = true}
