[package]
name = "opsml-state"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[lib]
doctest = false

[dependencies]
opsml-client = { workspace = true }
opsml-types = { workspace = true }
opsml-settings = { workspace = true }
opsml-toml = { workspace = true }
opsml-utils = { workspace = true }

futures = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

